name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tmate-session:
    runs-on: ubuntu-latest

    steps:
      - name: Set up tmate session
        run: |
          sudo apt update || true
          sudo apt install tmate -y || true
          tmate -F
