name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tmate and start session
        run: |
          sudo apt update || true && \
          sudo apt install tmate -y || true && \
          clear && tmate -F
